import {StyleSheet} from 'react-native';
import {Colors} from '../../shared/Colors';

export const styles = StyleSheet.create({
  modal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  container: {
    backgroundColor: Colors.BACKGROUND,
    padding: 25,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    height: '80%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    zIndex: 2,
  },
  headerText: {
    color: Colors.PRIMARY,
    fontSize: 18,
    fontWeight: '500',
    fontFamily: 'OatmealPro-Medium',
  },
  more: {
    backgroundColor: Colors.SECONDARY,
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    width: 32,
    borderRadius: 100,
  },
  selectedBox: {
    width: 151,
    height: 151,
    backgroundColor: Colors.SECONDARY,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerBox: {
    width: 151,
    height: 151,
    backgroundColor: Colors.SECONDARY,
    borderRadius: 10,
  },
  bottomContainer: {
    justifyContent: 'flex-end',
    zIndex: 1,
  },
  deleteButton: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 50,
    padding: 12,
    backgroundColor: Colors.SECONDARY,
    borderRadius: 24,
    height: 48,
    width: 129,
  },
  deleteText: {
    alignItems: 'center',
    color: Colors.ERROR,
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'OatmealPro-Regular',
  },
  dropdown: {
    backgroundColor: Colors.SECONDARY,
    paddingHorizontal: 14,
    paddingVertical: 14,
    height: 52,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 0,
  },
  dropdownContainer: {
    backgroundColor: Colors.SECONDARY,
    borderWidth: 0,
    zIndex: 1000,
  },
  selectedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  dropdownItemIcon: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
  selectedItemText: {
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 10,
  },
  input: {
    backgroundColor: Colors.SECONDARY,
    paddingHorizontal: 16,
    paddingVertical: 12,
    height: 52,
    borderRadius: 8,
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    marginBottom: 20,
    backgroundColor: Colors.SECONDARY,
    borderRadius: 40,
    height: 64,
  },
  selectedIcon: {
    position: 'absolute',
    top: 15,
    left: 15,
    width: 40,
    height: 40,
  },
  selectedUsername: {
    alignSelf: 'center',
    position: 'absolute',
    bottom: 10,
    fontSize: 14,
    fontWeight: '500',
    color: Colors.Black,
  },
  close: {
    color: Colors.Grey,
    fontSize: 14,
    alignItems: 'center',
    fontWeight: '500',
    fontFamily: 'OatmealPro-Medium',
    padding: 10,
  },
  saveButton: {
    backgroundColor: Colors.PRIMARY,
    borderRadius: 128,
    paddingHorizontal: 24,
    paddingVertical: 10,
    height: 40,
    gap: 8,
    opacity: 0.5,
  },
  save: {
    color: Colors.WHITE,
    fontSize: 14,
    alignItems: 'center',
    fontWeight: '500',
    fontFamily: 'OatmealPro-Medium',
  },
});
